### ISSUE TITLE
exception on android

### ISSUE THREAD

**Issue by danielwalczak** [amondnet/flutter_mixpanel#4]
I got this issue which makes this plugin not working completely on android

```
E/DartMessenger(12409): java.lang.IllegalStateException: when (type) {  
E/DartMessenger(12409):       DATE…fType(type, buffer)                  
E/DartMessenger(12409):     } must not be null                          
E/DartMessenger(12409):         at net.amond.flutter_mixpanel.MixpanelMessageCodec.readValueOfType(FlutterMixpanelPlugin.kt:215)
E/DartMessenger(12409):         at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:319)
E/DartMessenger(12409):         at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:412)
E/DartMessenger(12409):         at net.amond.flutter_mixpanel.MixpanelMessageCodec.readValueOfType(FlutterMixpanelPlugin.kt:223)
E/DartMessenger(12409):         at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:319)
E/DartMessenger(12409):         at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:48)
E/DartMessenger(12409):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/DartMessenger(12409):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(12409):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/DartMessenger(12409):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(12409):         at android.os.MessageQueue.next(MessageQueue.java:335)
E/DartMessenger(12409):         at android.os.Looper.loop(Looper.java:183)
E/DartMessenger(12409):         at android.app.ActivityThread.main(ActivityThread.java:7656)
E/DartMessenger(12409):         at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(12409):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/DartMessenger(12409):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (12409): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method track on channel net.amond.flutter_mixpanel)
E/flutter (12409): #0      FlutterMixpanel.track (package:flutter_mixpanel/src/mixpanel.dart:26:7)
E/flutter (12409): <asynchronous suspension>                            
```

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[✓] Connected device (1 available)
    ! Error: Daniel Walczak’s iPhone pro is not connected. Xcode will continue when Daniel Walczak’s iPhone pro is connected. (code -13)

• No issues found!
````

**Comment by danielwalczak** [comment]
I have cleaned the data I set for person, and it seems to solve the issue.
